### PR TITLE
Handle EntityCombustByEntity events

### PR DESCRIPTION
**Pull request by bigpresh**
This is my work to try to fix ticket 1064, where animals in claims were killable by fire damage using an enchanted bow since some recent Spigot changes: http://dev.bukkit.org/bukkit-plugins/grief-prevention/tickets/1064-flaming-arrows-kill-animals-in-claims-since-recent/

It's a bit messy so far, but appears to work on my test server.

I'd be happy for feedback on this.  If you think the general approach is sane, I can try to tidy it up a bit to meet GP's coding standards, if you'll share them with me.  Or, if you prefer to merge it and run it through a Java tidier in your IDE of choice, go right ahead :)

### CODE REVIEW

**Comment by ryanhamshire** [comment]
Hey, big thanks for trying to take on a tough problem - nobody likes refactoring legacy code!  And also for being so helpful with the forums lately.  I'm thrilled when people give me a reproducible bug report, and you've gone an order or magnitude farther.

Rather than trying to make lots of small changes, I decided to largely re-use the existing code without change by creating a fake EntityDamageByEntity event based on the combustion event and passing that through the existing well-tested code without significant changes.  That way I can feel confident about it working without risking breaking older code.  The problem was then double-messaging, so I added a parameter to silence the messages for one of the two event handlers.  This way I don't have to worry about what minor bits I may have missed, and the code change is smaller.  I think I remember doing a similar thing back when the Spigot team changed the API for how players interact with armor stands and it seems to have worked well because I didn't have to revisit that area.

Cheers!

**Comment by ryanhamshire** [comment]
Oh, I didn't see the .getName() thing.  Is economy integration broken?  Did Vault change their API again?

**Comment by bigpresh** [comment]
Happy to help, as I say, GP has been invaluable on our server.

Your approach sounds like a good way to implement it with less changes required - wish I'd thought of that :)  Oddly, I don't see the commit(s) with your fixes on Github, though - did you forget to push them or something?

Regarding the .getName() additions, it would seem so - it didn't compile without that.  We don't actually use an economy, so all I can say is that it doesn't compile for us without those, but does with them.

**Comment by bigpresh** [comment]
Closing this now you merged my other PR (thanks!) which also had the .getName() additions which you re-opened this PR for.

**Pull request closed without merging**
