### PR TITLE
[Request] Add Player Command

### PR DESCRIPTION
**Pull request by DrSnowPengu**
Grief Prevention Author I have really good suggestion. I was wondering If you can add command where players can give there own claims to other players. Is there way you can add that command? I think it would be great idea. :)

Thank You!

### CODE REVIEW

**Comment by RoboMWM** [comment]
Yea don't do this

**Comment by LaxWasHere** [comment]
¯\_(ツ)_/¯

**Comment by RoboMWM** [comment]
@AccioAce Please close this pull request

**Comment by RoboMWM** [comment]
@AccioAce Please close this

**Comment by sirlinium** [comment]
Hello,

would it be possible to be able to disable the /trapped use ?

many thanks !

**Comment by RoboMWM** [comment]
@AccioAce Please close this "pull request"

**Comment by sirlinium** [comment]
excuse me, wrong place ? or won't be possible ? (or juste no time)

**Comment by RoboMWM** [comment]
Yes, wrong place. Plugin is no longer developed here but at https://github.com/techfortress/GriefPrevention

@AccioAce somehow made this PR with _my_ branch just so he could restate his request to the original repo. Idk why other than obviously not paying attention to what he was doing... He already made such a request on the proper issue tracker https://github.com/TechFortress/GriefPrevention/issues/74 but I guess he decided to... idk, repeat the request wherever else he could...

**Comment by RoboMWM** [comment]
@AccioAce I know you're here, close this please.

**Pull request closed without merging**
