### PR TITLE
make getChunkString unique

### PR DESCRIPTION
**Pull request by Slind14**
I ran into issues where claims were reported to be existing in a chunk where non were e.g. (in chunk coords)

137,2 = 1372
13,72 = 1372

### CODE REVIEW

**Comment by ryanhamshire** [comment]
Why do you see this as a problem?  What negative impact do you see because of this?

**Comment by RoboMWM** [comment]
My guess is that there's no way to distinguish between chunk coordinate 137,2 and 13,72 for example.

Though I'm still trying to determine how you're figuring out (and where you're storing) chunk coordinates in the code. 2.9 year later edit: He's doing this to reduce claims to loop through when finding a claim at a location.

Edit: Oh, you have the first argument returning a string...?

**Comment by Slind14** [comment]
We ran into the issue of players not being able to expand their claim due to a claim at the other side of the world being in a chunk which got the same identifier. This might only be an issue with addons, though. But overall this small change shouldn't cause any issues. It doesn't mess around with save data nor are the methods public/static

**Comment by RoboMWM** [comment]
~~@Slind14 it seems he returns the first argument (coordinate x) as a string, while leaving z as an int. Perhaps you could use that to differentiate? (or am I just being stupid here)~~
Wow 2.9 years younger me, u rly stoopid.

**Comment by Slind14** [comment]
I'm already using what I put in as pull req on a server with +300 concurrent players and it works without issues so far.

**Comment by ryanhamshire** [comment]
Yep its safe enough but this is critical path for performance.  I'll try to reproduce your outside and fix it downstream instead to avoid a perf setback.

**Comment by Slind14** [comment]
hmm, you store it as String in the map and not as integer, if you care about perf, you might want to change it to int

**Comment by KaiKikuchi** [comment]
Hello. You can convert the x and z coords to a single long value using bitshift operators, and use a Long object as a key for the chunksToClaimsMap.
This is the method I use to convert the x and z coords to a single long:
https://github.com/KaiKikuchi/GriefPreventionPlus/blob/master/src/main/java/net/kaikk/mc/gpp/DataStore.java#L1570

Using a long value instead of a string will improve performances and it makes the "getChunkString" (maybe it should be called getChunkLong) method unique. This doesn't need a new class (but the ChunkCoord class suggested is a good alternative, but you have to define a good hashCode() method so the HashMap won't have bad performances.) nor defining an hashCode() method because the Long class has it's own hashCode() already.

**Comment by Slind14** [comment]
I did not want to mess around with it too much, but also didn't think about the performance impact. Now that I see what it is all used for.

**Comment by RoboMWM** [comment]
Ok now this PR is a mess... you've undid some of his newest additions...

**Comment by Slind14** [comment]
only the once from the beginning of this pull req

**Comment by ryanhamshire** [comment]
Wow, lots of thread here.  Let me just get everybody on the same page.  A chunk string isn't supposed to be unique to a chunk, and it wouldn't be unless the world name were also included (the name is bad).  The reason it's a string is because at some point in the past, I did include the world name.  I dropped the world name to save perf on getting the name and concatenating it.  I will check to see if I can find any issues with the current code in grief prevention, probably using chunks 11,1 and 1,11.  If I find any, I'll fix them in GP but upstream where the problem is, not by sacrificing perf on determining the chunk string.  And I really like the idea of concatenating two ints into a long - after I've corrected any upstream problems, I'll come back to this and profile it to make sure it's faster before finalizing the change.  If chunk strings are currently public, I'll probably hide them and provide better API's instead to help addon developers avoid this confusion in the future (at the cost of breaking some in the short term).

Thanks, everyone!

**Comment by Slind14** [comment]
using a seperator would at max have a 50% perf impact and that only in the case of single number coords.

The other way with an object or bit pushing is way better than what there is atm, regarding performance. I'm sorry, but I don't really understand why you see it as such a big performance issue. Especially as it can be improved (object or bit pushing).

**Comment by ryanhamshire** [comment]
Even a 10% setback would be a big deal.  This function is at the core of every claim search - every time a player right clicks a block, tries to place or break a block, attacks or interacts with an animal.  Up to five times for EACH piston extension.  Up to four times each time a fluid block tries to spread (which is a recursive process).  Scary stuff.  I've been profiling the plugin regularly over the last year, and I keep coming back to this method being the single biggest potential impact on overall CPU cost for running the plugin.  That's what I'm excited about the idea of concatenating ints into longs instead of first converting them into strings and then concatenating the strings.  I assume it will be much faster, but I gotta build a couple of profiles for comparison to make sure.  Maybe I can get it done tomorrow evening.

Adding a separator doesn't solve the problem you want to solve because if you have three worlds for example, then you'll still have collisions sometimes.  The only way to get a unique ID for each chunk would be to factor in a world identifier as well, so just adding a separator costs perf without giving you the uniqueness that you want.  Even if it did, it wouldn't be worth the perf setback because callers have to check claim boundaries with or without the separator change (even with the separator change, there can be as many as 16x16 = 256 claims in each chunk, then multiplied by the number of worlds where claims are enabled).

Also, we get the same benefit as adding a separator by going with the concatenating ints approach.

**Comment by Slind14** [comment]
alright, thanks for the explanation. We use gp only in one world and hence didn't run into any issues regarding multiple worlds. I check the addons source to determine if this is the case and if not dig further into it. 
Regarding the object or bit pushing, Wouldn't that still be way more performant than the string and hence might be something to think about.

**Comment by KaiKikuchi** [comment]
It'll be definitely way more performant... I tested that 1 year ago.

**Comment by Slind14** [comment]
@ryanhamshire @KaiKikuchi What about doing it with a custom object. int x, int z, UUID worldUUID. Equals should be faster as it is with strings atm and hashing shouldn't be a problem either. It would make it fully unique and the second method call would not be required. I believe that overall it would be performing better and reduce complexity.

**Comment by KaiKikuchi** [comment]
@Slind14 I think you miss the point of having chunksToClaimsMap. Also the most important thing for an HashMap is the key's hashCode() method. You have to generate a very good hash code or you'll get bad performances, much worse than current String. The world uuid on the key isn't needed at all.

When calling chunksToClaimsMap.get(ChunkCoords), you'll get a List of claims in that chunk coords. In fact, there can be more claims on the same chunk coords. Also even if a claim is on the chunk, it doesn't mean it overlaps another chunk, so you still have to check if the claim in the claims list contains the block coord you're going to "use" somewhere else. When doing this, you can check the world too.

> I think your problem must be unique to a GP addon where the developer makes the mistake of assuming that he doesn't have to check claim.contains() after determining that a claim is in the chunk he's interested in.

^ I think this is your issue, definitely. The chunk string currently used is not the best way, but it won't cause your issue.

**Comment by Slind14** [comment]
I bet it performs better although it contains more. Made another branch for it to be clear.
https://github.com/ryanhamshire/GriefPrevention/pull/39

**Comment by KaiKikuchi** [comment]
It performs better only if there are a lot of hash code collisions.
At this moment, the "main" collision is "being on the same chunk coords in more worlds".
With your object, the "main" collision is "being on the same chunk coords".

Remeber your object will cause an overhead (a new class and a new object, and more methods called), more memory use, and it needs to calculate the hash code including the UUID.

In your server, you said you use claims in one world only. That means in your server will perform worse than without the uuid.

Also my from2int method is not the best... I found a better way.

**Comment by Slind14** [comment]
Yeah, it doesn't matter that much regarding GP on its own. Anyways I'm using the fork, I just thought this might help the original GP version.

To explain you the issue. The addon shouts out warnings when you build in a chunk that contains a block.This is because chunks with relation to a claim can be deleted and rolled back and it should not impact others that are building near by.

Lets consider it is reporting 3 claims, e.g. one at world:11,12 another at world:1,112 and one more at nether:11,12. The chunk we are checking against is world:11,-12. 
In order to verify that there is a claim in the chunk we need to iterate over the claims including all possible locations. We end up with 3x16x16 = claim.contains() method calls on every interact event. 
I hope that makes sense to you, now.

**Comment by KaiKikuchi** [comment]
It doesn't need to use 768 claim contains()... just don't use contains() but a custom method that checks by chunk coords, not by block coords. And anyway it's still an addon issue. There can be more claims inside the same chunk in the same world.

**Comment by KaiKikuchi** [comment]
This would be how I would check it:
```java
void trigger(Block block) { // method called when there's your block trigger
	Collection<Claim> list = dataStore.getClaims(block.getBlockX()>>4, block.getBlockZ()>>4);
	for (Claim claim : list) { // your example includes 3 claims in this list, but one is the correct claim
		if (claim.getLesserBoundaryCorner().getWorld()==block.getWorld()) { // check if it's the same world
			if (claim.getLesserBoundaryCorner().getLocation().getBlockX()>>4 == block.getBlockX()>>4 && claim.getLesserBoundaryCorner().getLocation().getBlockZ()>>4 == block.getBlockZ()>>) {
				// here's the code for your only claim in your example
			}
		}
	}
}

**Comment by Slind14** [comment]
Wouldn't that only check if the chunk starts (lesser corner) in the same chunk as the clicked block is? 
Assuming the second check should be getGreaterBoundaryCorner including where it ends. So if the claim is stretched across more than 2 chunks it wouldn't work.

**Comment by KaiKikuchi** [comment]
Yeah it was just an example showing you can check if the block is in the same chunk of a claim. You can use a for loop to check all chunks from the lesser corner to the greater corner.

**Comment by Slind14** [comment]
yeah, we both came from different angels. When I put in this pull req I didn't even know what it was really used for. The addon used the one collection that had the information in a format required not knowing about it not being unique and further verification steps being required. So I thought it should be unique because I ran into those issues. I'm just gonna close it and @ryanhamshire can see for him self if changing it for better performance is worth it or not.

**Pull request closed without merging**
